export const endpoints = {
  auth: {
    me: "/auth/me",
    login: "/auth/login",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    discordCallback: "/auth/discord/callback",
  },
  guilds: {
    list: "/guilds",
    byId: (guildId: string) => `/guilds/${guildId}`,
    settings: (guildId: string) => `/guilds/${guildId}/settings`,
    stats: (guildId: string) => `/guilds/${guildId}/stats`,
    recentMembers: (guildId: string) => `/guilds/${guildId}/members/recent`,
    memberStats: (guildId: string) => `/guilds/${guildId}/members/stats`,
    boosterRoleMe: (guildId: string) => `/guilds/${guildId}/boosters/me`,
    boosterRoles: (guildId: string) => `/guilds/${guildId}/boosters`,
    boosterSettings: (guildId: string) => `/guilds/${guildId}/boosters/settings`,
    boosterSync: (guildId: string) => `/guilds/${guildId}/boosters/sync`,
    categories: (guildId: string) => `/guilds/${guildId}/channels/categories`,
    actions: (guildId: string) => `/guilds/${guildId}/actions`,
    tempVoice: (guildId: string) => `/guilds/${guildId}/voice/temp`,
    roles: (guildId: string) => `/guilds/${guildId}/roles`,
    textChannels: (guildId: string) => `/guilds/${guildId}/channels/text`,
    autoRoles: (guildId: string) => `/guilds/${guildId}/autoroles`,
    welcomes: (guildId: string) => `/guilds/${guildId}/welcomes`,
    welcomeBackground: (guildId: string) => `/guilds/${guildId}/welcomes/background`,
    moderation: (guildId: string) => `/guilds/${guildId}/moderation`,
    moderationPermissions: (guildId: string) => `/guilds/${guildId}/moderation/permissions`,
    moderationPurge: (guildId: string) => `/guilds/${guildId}/moderation/purge`,
    moderationNuke: (guildId: string) => `/guilds/${guildId}/moderation/nuke`,
    moderationLogs: (guildId: string) => `/guilds/${guildId}/moderation/logs`,
    moderationWhitelist: (guildId: string) => `/guilds/${guildId}/moderation/whitelist`,
    moderationFilters: (guildId: string) => `/guilds/${guildId}/moderation/filters`,
    moderationAutoPunishments: (guildId: string) => `/guilds/${guildId}/moderation/auto-punishments`,
    moderationLogChannel: (guildId: string) => `/guilds/${guildId}/moderation/log-channel`,
    monthlyJoins: (guildId: string) => `/guilds/${guildId}/members/joins/monthly`,
    auditLogs: (guildId: string) => `/guilds/${guildId}/audit-logs`,
    ranking: (guildId: string) => `/guilds/${guildId}/ranking`,
    logging: (guildId: string) => `/guilds/${guildId}/logging`,
    leveling: (guildId: string) => `/guilds/${guildId}/leveling`,
    messageSender: (guildId: string) => `/guilds/${guildId}/messages/send`,
    giveaways: (guildId: string) => `/guilds/${guildId}/giveaways`,
    giveawayById: (guildId: string, giveawayId: string) => `/guilds/${guildId}/giveaways/${giveawayId}`,
    giveawayParticipants: (guildId: string, giveawayId: string) => `/guilds/${guildId}/giveaways/${giveawayId}/participants`,
    giveawayRoll: (guildId: string, giveawayId: string) => `/guilds/${guildId}/giveaways/${giveawayId}/roll`,
    premium: (guildId: string) => `/guilds/${guildId}/premium`,
    works: (guildId: string) => `/guilds/${guildId}/works`,
  },
  bot: {
    status: "/bot/status",
    stats: "/bot/stats",
  },
  owner: {
    metrics: "/owner/metrics",
  },
} as const;
